### ISSUE TITLE
Incorrect Label Value – <fullName>labelVolunteerSignupThankYou</fullName> 

### ISSUE THREAD

**Issue by josefjoy** [davidhabib/Volunteers-for-Salesforce#122]
Hello,

Great app. 

The value of the submit-thank you message doesn't make grammatical sense. Can you update to "Thank you for signing up." or something similar? Apologies if there is a way to edit this in the installed package and I'm just not seeing it. Thanks! 

<fullName>labelVolunteerSignupThankYou</fullName>
<categories>VolunteersSignupFS, VolunteersJobListing</categories>
<language>en_US</language>
<protected>false</protected>
<shortDescription>Thank you message displayed after a successful Volunteer Signup on the web</shortDescription>
<value>Thank you for signing up for volunteering.</value>

**Comment by davidhabib** [comment]
since it is a custom label, you can use translation workbench to update the
english version to whatever you'd like.  details in the installation &
configuration guide.  the next time I am working on new features, I'll
update this label.  but for now, you have a workaround.


David Habib | Senior Force.com Developer | salesforcefoundation.org

**Comment by josefjoy** [comment]
Fantastic, thanks so much!

**Comment by davidhabib** [comment]
re-opened so I remember to update the label.

**Comment by davidhabib** [comment]
Fixed in release 3.75
