### ISSUE TITLE
Error - No such column 'lastvieweddate' on entity 'GW_Volunteers__Volunteer_Hours__c'

### ISSUE THREAD

**Issue by JayantaP** [davidhabib/Volunteers-for-Salesforce#197]
Since last week I'm getting this error on Personal Site Contact Info page:
No such column 'lastvieweddate' on entity 'GW_Volunteers__Volunteer_Hours__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

Not sure what's wrong.
We are using a sandbox with Summer '16. Is it because of API version mismatch?

![personalsiteerrormsg](https://cloud.githubusercontent.com/assets/7793951/16031712/f7381580-321b-11e6-9520-7f8e74af499d.png)

Regards,
Jay

**Comment by davidhabib** [comment]
we've seen this type of error before in the nonprofit starter pack with some api versioning issues in Salesforce.  I assume you are running the managed package rather than unmanaged code.  I'm not able to reproduce this problem.  I'd start to narrow it down by removing all your fields from the various field sets that the page is using to see if that helps.  then add them back making sure not to include lastvieweddate.  I'd also recommend you test all of the other Sites pages and see if you are also getting similar issues, or whether it is specific to just PersonalSitecontactInfo.  Also, do you have V4S installed into your production org, or just the sandbox?  does the same problem occur in production?  I assume production also got upgraded to Summer '16 in the last week.

**Comment by JayantaP** [comment]
Thank you very much David. You saved my day. 
I removed all additional fields from field sets PersonalSiteContactInfoHistory and PersonalSiteContactInfoUpcomingShifts and it started working. 
I'm not sure though why this happened. The field sets did not have lastvieweddate or any formula fields.
I'm using V4S in the org. Right now we are developing in a sandbox and has not moved to prod yet. We'll test there once we deploy.
